version: '3.8'

services:
  spark:
    image: bitnami/spark:3.5.0
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"   # Spark Web UI
      - "7077:7077"   # Spark master port
    networks:
      - cloudjet-net
    volumes:
      - ../:/home/jovyan/work

  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark
    networks:
      - cloudjet-net
    volumes:
      - ../:/home/jovyan/work

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ../:/home/jovyan/work  # ✅ mount โค้ดแค่ jupyter เท่านั้น
    depends_on:
      - spark
      - spark-worker
    networks:
      - cloudjet-net

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    networks:
      - cloudjet-net

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cloudjet-net

volumes:
  minio-data:
  pgdata:

networks:
  cloudjet-net:
